---
- name: Ensure httpd, mod_ssl and php packages are installed
  # package module uses yum automatically on RHEL and apt on ubuntu.
  ansible.builtin.package:
    name:
      - httpd
      - mod_ssl
      - php
    state: present

- name: Ensure apahce service is running and enabled on boot
  ansible.builtin.service:
    name: apahce
    state: started
    enabled: true

- name: Configure firewall to allow all incoming traffic on HTTP and HTTPS.
  ansible.builtin.firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  loop:
    - http
    - https